In [13]:
import pandas as pd
from glob import glob
import copy
import numpy as np

In [14]:
df = pd.read_csv("../data/train.csv")

In [15]:
df.head()

doc_id                                              titre  \
0  recette_221358.xml  Feuilleté de saumon et de poireau, sauce aux c...   
1   recette_48656.xml                       Cake poulet/moutarde/amandes   
2   recette_30049.xml           Bûche à la truite fumée (7ème rencontre)   
3   recette_71424.xml    Gâteau au yaourt au coco sans huile de laetitia   
4  recette_217204.xml                             Crêpes au canard laqué   

             type             difficulte        cout  \
0  Plat principal                 Facile       Moyen   
1          Entrée            Très facile  Bon marché   
2          Entrée  Moyennement difficile  Assez Cher   
3         Dessert            Très facile  Bon marché   
4          Entrée  Moyennement difficile       Moyen   

                                         ingredients  \
0  - 1 gros pavé de saumon - 100 g de crevettes d...   
1  - 3 œufs - 150 g de farine - 1 sachet de levur...   
2  - 800 g de filet de truite saumonnée fumée en ...   
3  - 1 pot de yaourt - 1 pot de lait de coco - 3 ...   
4  - 90 g de farine - 45 g de maïzena - 2 œufs - ...   

                                             recette  
0  Couper finement le blanc et un peu de vert des...  
1  Couper finement l'échalote, la faire revenir à...  
2  Faites blanchir les épinards à l'eau bouillant...  
3  Mélanger dans l'ordre tous les ingrédients en ...  
4  Fouetter les œufs avec l'eau, le lait et le su...

In [16]:
df_entree = df.loc[df['type'] == "Entrée"]
df_pp = df.loc[df['type'] == "Plat principal"]
df_dessert = df.loc[df['type'] == "Dessert"]

rand_entree = copy.deepcopy(df_entree.index.values)
rand_pp = copy.deepcopy(df_pp.index.values)
rand_dessert = copy.deepcopy(df_dessert.index.values)

np.random.shuffle(rand_entree)
np.random.shuffle(rand_pp)
np.random.shuffle(rand_dessert)

In [17]:
print(rand_entree)
print(rand_pp)
print(rand_dessert)

[ 7820 10138  5909 ...  6500  6481  4916]
[ 9533  2875 10893 ...  4245   330   977]
[ 4663 11076  8138 ...  6745 10804 11590]


In [18]:
print(len(rand_entree))
print(len(rand_pp))
print(len(rand_dessert))

2909
5802
3762


In [19]:
idx_entree = int(len(rand_entree) * 0.8)
idx_pp = int(len(rand_pp) * 0.8)
idx_dessert = int(len(rand_dessert) * 0.8)

In [20]:
df_entree_train = df_entree.loc[rand_entree[:idx_entree]]
df_pp_train = df_pp.loc[rand_pp[:idx_pp]]
df_dessert_train = df_dessert.loc[rand_dessert[:idx_dessert]]

df_entree_test = df_entree.loc[rand_entree[idx_entree:]]
df_pp_test = df_pp.loc[rand_pp[idx_pp:]]
df_dessert_test = df_dessert.loc[rand_dessert[idx_dessert:]]

In [21]:
df_train = pd.concat([df_entree_train, df_pp_train, df_dessert_train])
df_test = pd.concat([df_entree_test, df_pp_test, df_dessert_test])

In [22]:
np.random.shuffle(rand_entree)
idx_train = copy.deepcopy(df_train.index.values)
idx_test = copy.deepcopy(df_test.index.values)
np.random.shuffle(idx_train)
np.random.shuffle(idx_test)
df_train = df_train.loc[idx_train]
df_test = df_test.loc[idx_test]

In [23]:
df_entree_test.to_csv("../data/test/data_entree.csv", index=False)
df_pp_test.to_csv("../data/test/data_pp.csv", index=False)
df_dessert_test.to_csv("../data/test/data_dessert.csv", index=False)
df_test.to_csv("../data/test/test.csv", index=False)

df_entree_train.to_csv("../data/train/data_entree.csv", index=False)
df_pp_train.to_csv("../data/train/data_pp.csv", index=False)
df_train.to_csv("../data/train/train.csv", index=False)